SELECT CLI_SEXO AS SEXO, COUNT(CLI_SEXO) AS QUANTOS FROM CLIENTE GROUP BY CLI_SEXO;

SELECT 'DO SEXO ' || CLI_SEXO || ' TEM' AS "PESSOAS DO SEXO", COUNT(CLI_SEXO) 
AS QUANTIDADE FROM CLIENTE GROUP BY CLI_SEXO;

SELECT CLI_SEXO AS SEXO, AVG(CLI_SALARIO) AS MEDIA_SALARIAL FROM CLIENTE GROUP BY CLI_SEXO;

SELECT CLI_SEXO AS SEXO, SUM(CLI_SALARIO) AS SOMA_SALARIO, AVG(CLI_SALARIO) AS MEDIA,
COUNT(CLI_SEXO) AS "QUANTIDADE DE PESSOAS" FROM CLIENTE GROUP BY CLI_SEXO;


SELECT BAI_NOME AS BAIRRO, CLI_SEXO AS SEXO, SUM(CLI_SALARIO) AS SOMA, 
AVG(CLI_SALARIO) AS MEDIA,
COUNT(CLI_SEXO) AS "QUANTIDADE DE PESSOAS" FROM CLIENTE 
INNER JOIN BAIRRO ON BAI_CODIGO = CLI_BAIRRO
GROUP BY BAI_NOME, CLI_SEXO;


CREATE TABLE CIDADE (
    CID_CODIGO INTEGER NOT NULL,
    CID_NOME VARCHAR(30) NOT NULL,
    CONSTRAINT CHAVE_PRIMARIA_CIDADE PRIMARY KEY(CID_CODIGO)
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_BAIRRO FOREIGN KEY(CLI_BAIRRO) 
REFERENCES BAIRRO (BAI_CODIGO);

SELECT * FROM CLIENTE;

DESCRIBE CLIENTE;