CREATE TABLE BAIRRO (
    bai_codigo integer not null,
    bai_nome varchar(30),
    constraint chave_primaria_bairro primary key (bai_codigo)
);

SELECT * FROM BAIRRO;

INSERT INTO BAIRRO VALUES ( 1, 'CENTRO');

INSERT INTO BAIRRO VALUES ( 2, 'ZONA SUL');

INSERT INTO BAIRRO VALUES ( 3, 'SANTA BÁRBARA');

INSERT INTO BAIRRO VALUES ( 4, 'ZONA OESTE');
`
describe bairro;

CREATE TABLE CLIENTES(
    cli_codigo integer not null,
    cli_nome varchar(30),
    cli_bairro integer not null,
    cli_sexo char(1),
    constraint chave_primaria_cliente primary key (cli_codigo)
);
/*DESCRIBE*/
describe clientes;

INSERT INTO CLIENTES VALUES (1, 'MARCOS DANIEL', 1, 'M');

INSERT INTO CLIENTES VALUES (2, 'JOAO DA SILVA', 2, 'M');

INSERT INTO CLIENTES VALUES (3, 'MARIA JOANA',  3, 'F');

SELECT * FROM CLIENTES;

/*DELETE FROM BAIRRO WHERE BAI_CODIGO = 4;*/

SELECT * FROM BAIRRO;

SELECT * FROM CLIENTES ORDER BY CLI_SEXO;

SELECT * FROM CLIENTES ORDER BY CLI_NOME;

SELECT * FROM CLIENTES WHERE CLI_CODIGO = 2;

SELECT * FROM CLIENTES WHERE CLI_NOME LIKE '%J%';

SELECT * FROM CLIENTES WHERE CLI_CODIGO NOT BETWEEN 2 AND 5;

SELECT * FROM CLIENTES WHERE CLI_CODIGO BETWEEN 2 AND 5;

/*CONTANTO QUE O CODIGO SEJA 1 OU 3*/
SELECT * FROM CLIENTES WHERE CLI_CODIGO IN (1,3);

/*CONTANTO QUE O CODIGO NAO SEJA 1 OU 3*/
SELECT * FROM CLIENTES WHERE CLI_CODIGO NOT IN (1,3);

/*DISTINCT*/
SELECT DISTINCT CLI_SEXO FROM CLIENTES;


/*DROP TABLE WITH ORACLE
    DROP CLIENTES
*/

/*
ALTER TABLE
*/
ALTER TABLE CLIENTES ADD CLI_EMAIL VARCHAR (30);

SELECT * FROM CLIENTES;

/*UPDATE TABLE CLIENTES*/
UPDATE CLIENTES SET CLI_EMAIL = 'marcos.mdbbr@gmail.com' WHERE CLI_CODIGO = 1; 

/*
ALTER TABLE E DROP COLUMN WITH ORCL
*/
ALTER TABLE CLIENTES ADD CLI_TST VARCHAR(30);

ALTER TABLE CLIENTES DROP COLUMN CLI_TST;

UPDATE CLIENTES SET CLI_EMAIL = 'joao@teste.com.br' where cli_codigo = 2;

UPDATE CLIENTES SET CLI_EMAIL = 'maria@teste.com.br' where cli_codigo = 3; 

