CREATE TABLE USUARIO (
    USU_CODIGO INTEGER NOT NULL,
    USU_NOME VARCHAR(30) NOT NULL,
    USU_SENHA VARCHAR(30) NOT NULL,
    CONSTRAINT CHAVE_PRIMARIA_USUARIO PRIMARY KEY(USU_CODIGO)
);

SELECT * FROM USUARIO;

DESCRIBE USUARIO;

ALTER TABLE USUARIO ADD STATUS NOT NULL;

INSERT INTO USUARIO VALUES (1, 'MARCOSDANIEL', 'ADMINADMIN');

UPDATE USUARIO SET usu_nome = 'MARCOSDANIELBUDTINGER' WHERE usu_codigo = 1;

SELECT SUM(CLI_SALARIO) FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE;

SELECT AVG(CLI_SALARIO) FROM CLIENTE;

SELECT SUM(CLI_SALARIO) AS SALARIO_SEXO_MASCULINO FROM CLIENTE WHERE CLI_SEXO = 'M';
SELECT CLI_SALARIO AS SALARIO_SEXO_MASCULINO FROM CLIENTE WHERE CLI_SEXO = 'M';

SELECT MIN(CLI_SALARIO) FROM CLIENTE;

SELECT MAX(CLI_SALARIO) FROM CLIENTE;

SELECT CLI_CODIGO AS CODIGO, CLI_NOME AS NOME, UPPER(CLI_EMAIL) AS EMAIL, CLI_SEXO AS SEXO FROM CLIENTE;

/*
    CONCATENAÇÃO
*/
SELECT CLI_NOME || CLI_SEXO AS NOME_E_SEXO FROM CLIENTE;

SELECT CLI_NOME || '-' || CLI_SEXO AS "NOME E SEXO" FROM CLIENTE;

DESCRIBE CLIENTE;

CREATE INDEX IND_NOME_CLIENTE ON CLIENTE(CLI_NOME);




